image: docker:latest

variables:
  # Choose the official NGINX Ingress controller version you need here : https://github.com/kubernetes/ingress-nginx/blob/main/Changelog.md
  BASE_REPO: "k8s.gcr.io/ingress-nginx/controller"
  VERSION: "v0.49.3"
  YOUR_HUB: "TYPE_YOUR_HUB"

build:
  stage: build
  script:
    - docker build --pull -f Dockerfile -t ${YOUR_HUB}/nginx-ingress-controller:${VERSION}-${CI_PIPELINE_IID} . --build-arg BASE_REPO=${BASE_REPO} --build-arg VERSION=${VERSION}
    - docker push ${YOUR_HUB}/nginx-ingress-controller:${VERSION}-${CI_PIPELINE_IID}
  before_script:
    - docker login -u "${YOUR_USERNAME}" -p "${YOUR_PASSWORD}"
  when: manual
